<?php

if (!defined('DC'))
	die('!DC');

$lng[0] = 'English (US)';
$lng[1] = 'Afrikaans';
$lng[2] = 'Azərbaycan dili';
$lng[3] = 'Bahasa Indonesia';
$lng[4] = 'Bahasa Melayu';
$lng[5] = 'Basa Jawa';
$lng[6] = 'Bisaya';
$lng[7] = 'Bosanski';
$lng[8] = 'Català';
$lng[9] = 'Čeština';
$lng[10] = 'Cymraeg';
$lng[11] = 'Dansk';
$lng[12] = 'Deutsch';
$lng[13] = 'Eesti';
$lng[14] = 'English (UK)';
$lng[15] = 'Español';
$lng[16] = 'Español (España)';
$lng[17] = 'Euskara';
$lng[18] = 'Filipino';
$lng[19] = 'Français (Canada)';
$lng[20] = 'Français (France)';
$lng[21] = 'Galego';
$lng[22] = 'Guarani';
$lng[23] = 'Hrvatski';
$lng[24] = 'Italiano';
$lng[25] = 'Kiswahili';
$lng[26] = 'Latviešu';
$lng[27] = 'Lietuvių';
$lng[28] = 'Magyar';
$lng[29] = 'Nederlands';
$lng[30] = 'Norsk (bokmål)';
$lng[31] = 'Polski';
$lng[32] = 'Português (Brasil)';
$lng[33] = 'Português (Portugal)';
$lng[34] = 'Română';
$lng[35] = 'Shqip';
$lng[36] = 'Slovenčina';
$lng[37] = 'Slovenščina';
$lng[38] = 'Suomi';
$lng[39] = 'Svenska';
$lng[40] = 'Tiếng Việt';
$lng[41] = 'Türkçe';
$lng[42] = 'Ελληνικά';
$lng[43] = 'Български';
$lng[44] = 'Македонски';
$lng[45] = 'Русский';
$lng[46] = 'Српски';
$lng[47] = 'Українська';
$lng[48] = 'Հայերեն';
$lng[49] = '‏עברית‏';
$lng[50] = '‏اردو‏';
$lng[51] = '‏العربية‏';
$lng[52] = 'हिन्दी';
$lng[53] = 'বাংলা';
$lng[54] = 'ਪੰਜਾਬੀ';
$lng[55] = 'தமிழ்';
$lng[56] = 'తెలుగు';
$lng[57] = 'ಕನ್ನಡ';
$lng[58] = 'മലയാളം';
$lng[59] = 'සිංහල';
$lng[60] = 'ภาษาไทย';
$lng[61] = '한국어';
$lng[62] = '中文(台灣)';
$lng[63] = '中文(简体)';
$lng[64] = '中文(香港)';
$lng[65] = '日本語';

?>
